version: 2

builds:
  - id: rabbithole
    main: .
    binary: rabbithole
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/DanielBlei/rabbithole/cmd.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(?:\([[:word:]_-]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(?:\([[:word:]_-]+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999
